### PR TITLE
Fix refreshed access tokens not receiving `user` or `client` claims

### LINKED ISSUE #179: Fix swagger not applying the API version
Swagger does not apply v1 automatically to the endpoints. Swagger should be set to use v1 as the default.

### PR DESCRIPTION
**Pull request by myssto**
Since these claims are manually applied on creation, they need to be manually applied on refresh as well. This pull also addresses two smaller issues, populating the api version in swagger and removing the `/me/validate` endpoint (hence the breaking change tag).

Closes #179, #152

### CODE REVIEW

File: API/Handlers/Implementations/OAuthHandler.cs [hunk 1]
```diff
@@ -172,7 +172,7 @@ IUserRepository userRepository
             accessToken = GenerateAccessToken(
                 user.Id.ToString(),
                 _jwtAudience,
-                user.Scopes,
+                [.. user.Scopes, "user"],
```
Comment (hburn7) [inline API/Handlers/Implementations/OAuthHandler.cs:175]: Surprised this syntax works, didn't even know this was a thing.

**Review by hburn7 — APPROVED** [review]

File: API/Handlers/Implementations/OAuthHandler.cs (hunk 1 above)
Comment (myssto) [reply API/Handlers/Implementations/OAuthHandler.cs:175]: Yea me neither lol... I found it because the formatter automatically formatted `client.Scopes.Append("client").ToArray();` to `[.. client.Scopes, "client"];` so I guess we have to use it :P
